/**
 * Cross-platform replacement for res/css/rethemendex.sh (Windows has no `sh` in PATH).
 * Regenerates res/css/_components.pcss from underscore-prefixed .pcss files.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const cssDir = path.join(__dirname, "../res/css");

function* walk(dir) {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, ent.name);
        if (ent.isDirectory()) {
            yield* walk(full);
        } else {
            yield full;
        }
    }
}

const files = [...walk(cssDir)].filter((abs) => {
    const base = path.basename(abs);
    if (!/^_.+\.pcss$/i.test(base)) return false;
    const lower = base.toLowerCase();
    return lower !== "_components.pcss" && lower !== "_compound.pcss";
});

files.sort((a, b) => path.relative(cssDir, a).localeCompare(path.relative(cssDir, b), "en"));

const header = "/* autogenerated by scripts/rethemendex.mjs */";
const imports = files.map((abs) => {
    const rel = "./" + path.relative(cssDir, abs).split(path.sep).join("/");
    return `@import "${rel}";`;
});

fs.writeFileSync(path.join(cssDir, "_components.pcss"), [header, ...imports, ""].join("\n"));
